#!/bin/sh

source host_addr.sh

exec=''
while getopts "h:x:t:" Option
# b and d take arguments
#
do
case $Option in
x) exec=$OPTARG;;
h) host=$(addr $OPTARG);;
t) token=$OPTARG;;
esac
done
shift $(($OPTIND - 1))
echo "HOST:$host"
echo "CMD:$exec"

if [ -z ${token} ]; then
	token=`qc-cvm-token | grep '^[0-9]'`
	token="`echo ${token}`"
fi
echo "TOKEN:$token"
expect /usr/local/bin/to_expect $host $token "$exec"
#to.sh -h animal-w1 -x "bash -c 'echo animal'"
